### ISSUE TITLE
Can you provide us with a more detailed setup guide?

### ISSUE THREAD

**Issue by Lebedev21** [zKevz/GrowRust#2]
I have now succesfully built the server binary, but I cannot connect to the server.
I have set my windows hosts file to the correct settings and I have created a ```growtopia``` folder into my webserver's root directory and created a ```server_data.php``` file. I have also placed my ```items.dat``` file in the correct directory.

**Comment by AboodTBR** [comment]
![image](https://user-images.githubusercontent.com/68459641/155892828-799391cf-c481-4bb9-850f-1aa9d2340d67.png)

You've probably done something wrong with the http server.

Make sure `server_data.php` looks something like the following below
```
server|127.0.0.1
port|10000
type|1
#maint|Uncomment this in order to turn on maintenance mode.
beta_server|127.0.0.1
beta_port|17091
beta_type|1
meta|localhost
RTENDMARKERBS1001
```

**Comment by zKevz** [comment]
Unlike other open-sourced server which uses 17091 as its port, this one is using 10000 instead. That might be the issue on why you cant connect to the server
